### ISSUE TITLE
Incorrect error for server realm dev-dependencies

### ISSUE THREAD

**Issue by nezuo** [filiptibell/tooling-language-server#1]
When using a `dev-dependency` that belongs to the server realm, this error is reported:

"Package is a server dependency but is listed under `dev-dependencies.` Did you mean to list it under `server-dependencies`?"

This error isn't correct because there isn't a dev realm. In the wally readme, it says dev-dependencies can be `server` or `shared`: https://github.com/UpliftGames/wally/blob/ea536c5521fc514d7e6112d7037d8f18aae2f285/README.md?plain=1#L203

**Comment by filiptibell** [comment]
Fixed in https://github.com/filiptibell/tooling-language-server/commit/d9cdacaeb9b8c2b6c4b3fe39fd51f70534aedcd2
